name: Build Kivy Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip libffi-dev \
            libssl-dev libjpeg-dev \
            zlib1g-dev libncurses5 libncurses5-dev \
            libsqlite3-dev libreadline-dev \
            libgdbm-dev libbz2-dev liblzma-dev \
            libgmp-dev build-essential

      - name: Install Cython and Buildozer
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Initialize Buildozer
        run: |
          buildozer init || true

      - name: Patch Android SDK location (headless fix)
        run: |
          mkdir -p ~/.android && touch ~/.android/repositories.cfg

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build Android APK
        run: buildozer android debug
