name: Build Kivy Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install base dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            libncurses5 \
            libstdc++6 \
            zlib1g \
            libbz2-1.0

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      - name: Install Android SDK and accept licenses
        run: |
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "platform-tools" "build-tools;34.0.0"
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
        env:
          ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk
          PATH: $HOME/.buildozer/android/platform/android-sdk/platform-tools:$PATH

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: ./bin/*.apk
