name: Build Kivy Android App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip git python3-setuptools python3-wheel libncurses5 libstdc++6

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.36
        pip install buildozer

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p "$HOME"/android-sdk/cmdline-tools
        cd "$HOME"/android-sdk/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools.zip -d tools
        yes | tools/bin/sdkmanager --sdk_root="$HOME/android-sdk" --licenses
        tools/bin/sdkmanager --sdk_root="$HOME/android-sdk" "build-tools;33.0.2" "platforms;android-31" "platform-tools"
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/tools/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Initialize Buildozer (if not already)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: kivy-app-debug-apk
        path: bin/*.apk
